<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('LoS Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->losHeadLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->appendStylesheet($this->basePath() . '/css/style.css')
                        ->prependBootstrap()
                        ->appendFontAwesome() ?>

        <?php echo $this->losHeadScript()
            ->prependBootstrap()
            ->prependJquery(); ?>

            <?= $this->headStyle() ?>

    </head>
    <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="<?php echo $this->url('home',[],true) ?>" class="navbar-brand">
                        <img src="<?php echo $this->basePath('/img/zf2-logo.png') ?>" class="img-responsive">
                    </a>
                </div>

                <div class="collapse navbar-collapse nav-navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php echo $this->losNavigation()->menu('Navigation')->renderMenu(null,[])?>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?php echo $this->losNavigation()->breadcrumbs('Navigation')?>
            <?php echo $this->losflashmessenger()->renderAll()?>
            <?php echo $this->content; ?>
        </div>
        <nav class="navbar navbar-fixed-bottom" role="navigation">
            <div class="container">
                <p class="help-block">&copy; <?php echo date('Y')?> <a href="mailto://leandro@leandrosilva.info" target="_blank">Leandro Silva</a>. <?php echo $this->translate('All rights reserved.') ?></p>
            </div>
        </nav>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
